otime/urls.py
from django.urls import path
from .views import  index, salas, reservarHorario, professores, turmas, disciplinas, seletor_turmas, atualizar_professor, atualizar_disciplina, atualizar_sala, atualizar_turma
urlpatterns = [
    path("", index, name = "index"),
    path("salas", salas, name = "salas"),
    path("reservarHorario/<int:id>", reservarHorario, name = "reservarHorario"),
    path("professores", professores, name = "professores"),
    path("seletor_turmas", seletor_turmas, name = "seletor_turmas"),
    path("turmas", turmas, name = "turmas"),
    path("disciplinas", disciplinas, name = "disciplinas"),
    path('update/professor/<int:id>/', atualizar_professor, name='atualizar_professor'),
    path('update/disciplina/<int:id>/', atualizar_disciplina, name='atualizar_disciplina'),
    path('update/sala/<int:id>/', atualizar_sala, name='atualizar_sala'),
    path('update/turma/<int:id>/', atualizar_turma, name='atualizar_turma')
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("otime.urls")),
    path('admin/', admin.site.urls)  
]

Disciplina/models.py
from django.db import models

class Disciplina(models.Model):
    nome = models.CharField(max_length = 25)
    carga_horaria_total = models.IntegerField()
    def __str__(self):
        return "Disciplina #%d: %s" % (int(self.id), self.nome)

    class Meta:
        verbose_name_plural = "disciplinas"

Disciplina/views.py
from django.shortcuts import render
import requests

# Create your views here.
def listarDisciplinas(request):
    endereco = "http://localhost:8000/api/disciplinas"
    requisicao = requests.get(endereco)

    try:
        lista = requisicao.json()
    except ValueError:
        print("O formato da resposta não é o esperado.")

    dicionario = {}
    for indice, valor in enumerate(lista):
        dicionario[indice] = valor

    contexto = {
        "disciplinas": dicionario
    }

    return render(request, "disciplinas.html", contexto)

Disciplina/templates/disciplinas.html
<!DOCTYPE html>
{% load static%}
<html>
  <head>
        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href='{% static "otime/css/modal.css" %}'>
    <title>PIBIRITIBA</title>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href='{% static "otime/bootstrap/bootstrap.css" %}'>
    <link rel="stylesheet" href='{% static "otime/bootstrap/bootstrap.js" %}'>
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href='{% static "otime/css/estilo_professor.css" %}'>
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  </head>
  <body>
    <table id='minhaTabela'>
      <a href="/"><h2>PIBIRITIBA</h2></a>
        <thead>
          <tr>
            <th>DISCIPLINAS</th>
            <th><button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#myBtn4" onclick="salvarDisciplina()"> Nova </button></th>
          </tr>
        </thead>
        <tbody>
          {% for items, disciplina in disciplinas.items %}
            <tr>
              <td>{{ disciplina.nome }}</td>
              <td>
               <a href="update/disciplina/{{disciplina.id}}">Detalhes</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
       <div class="modal fade" id="myBtn4" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h3>NOVA DISCIPLINA</h3>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <form method="POST" onsubmit="return false">
                {% csrf_token %}
                <label for="id_nome">Nome:</label><input name="nome" maxlength="25" required="" id="id_nome" type="text">
                <label for="id_codigo">Codigo:</label><input name="codigo" maxlength="25" required="" id="id_codigo" type="text">
                <label for="id_carga_horaria_total">Carga horaria total:</label><input name="carga_horaria_total" required="" id="id_carga_horaria_total" type="number">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Fechar</button>
              <button class="btn btn-outline-success" onclick="salvarDisciplina()">Salvar</button>
              </form>
            </div>
          </div>
        </div>
      </div>

      </body>
      <!-- jQuery CDN - Slim version (=without AJAX) -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
      <script src='{% static "jquery/jquery.mim.js" %}'></script>
      <script src='{% static "jquery/jquery-3.2.1.slim.min.js" %}'></script>
      <script src='{% static "jquery/jquery.js" %}'></script>
      <!-- Popper.JS -->
      <script src='{% static "popper/popper.mim.js" %}'></script>
      <!-- Bootstrap JS -->
      <script src='{% static "bootstrap/js/bootstrap.js" %}'></script>
      <script src='{% static "bootstrap/js/bootstrap.bundle.min.js" %}'></script>
      <!-- javascript JS -->
      <script type="text/javascript">
      function salvarDisciplina() {
        requisicao = new XMLHttpRequest();
        requisicao.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 201) {
          json = JSON.parse(requisicao.response);
          id = json["id"];
          nome_objeto = json["nome"];

          tabela = document.getElementById("minhaTabela");
          nova_linha = tabela.insertRow();
          titulo = nova_linha.insertCell();
          detalhes = nova_linha.insertCell();

          titulo.innerHTML = nome_objeto;
          detalhes.innerHTML = "<a href='update/disciplina/" + String(id) + "'/>Detalhes</a>";
        }
      };
        requisicao.open("POST", '/api/disciplinas/', true);
        requisicao.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        nome = document.getElementById("id_nome").value;
        codigo = document.getElementById("id_codigo").value;
        carga_horaria_total = document.getElementById("id_carga_horaria_total").value;
        requisicao.send("csrfmiddlewaretoken=" + "{{ csrf_token }}" + "&nome=" + nome + "&codigo=" + codigo + "&carga_horaria_total=" + carga_horaria_total);
      };

      $(".rows").click
      (
        function(e)
        {
          window.location.replace($(this).data('href'));
          return false;
        }
      )
      </script>
      <script>
      $(document).ready(function(){
          $(".dropdown-toggle").dropdown();
      });
     </script>
</html>